title: J. Adly
markdown: kramdown
url: "https://youssefadly237.github.io"

# for atom feed
author:
  name: J. Adly
  email: youssefadly237@gmail.com

log_level: info

paginate: 5
paginate_path: "/page/:num/"

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

collections_dir: all_collections
collections:
  items:
    output: true
    permalink: /:title/
  hiddenposts:
    output: true
    permalink: /blog/:title/
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /blog/:title/

exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md", "drafts"]
